alias ls='ls --color=auto -l'
alias tls='tmux ls'
alias tn='tmux new -s'
alias ta='tmux attach -t'
alias td='tmux detach'
alias tk='tmux kill-session'
alias tks='tmux kill-session -t'
alias tka='pkill -f tmux'